---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: pushgateway
  name: pushgateway
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: pushgateway
    spec:
      containers:
        - name: pushgateway
          image: quay.io/prometheus/pushgateway:v1.6.0
          ports:
            - containerPort: 9091
              name: web
          resources: {}
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: web
          readinessProbe:
            httpGet:
              path: /-/ready
              port: web
