---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: pushgateway
  name: pushgateway
spec:
  endpoints:
    - interval: 30s
      port: http
      honorLabels: true
  namespaceSelector: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: pushgateway
