apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: simplest-collector
  name: simplest-collector
  namespace: demo-otel
spec:
  endpoints:
  - interval: 30s
    targetPort: 8888
    path: /metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: opentelemetry-collector
      operator.opentelemetry.io/collector-service-type: monitoring
