apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: demo-instrumentation
spec:
  exporter:
    endpoint: http://simplest-collector.demo.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: parentbased_traceidratio
    argument: "1"
  java:
    env:
      - name: QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://simplest-collector.demo.svc.cluster.local:4318
      - name: QUARKUS_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
        value: http://simplest-collector.demo.svc.cluster.local:4318
