apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-otel
  name: quarkus-otel
  namespace: demo-otel
spec:
  ports:
  - appProtocol: http
    name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: quarkus-otel
  sessionAffinity: None
  type: ClusterIP
