
default:
  envOverrides:
    - name: OTEL_COLLECTOR_NAME
      value: simplest-collector

opentelemetry-collector:
  enabled: false

jaeger:
  enabled: false

prometheus:
  enabled: false

grafana:
  enabled: false
