apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    app: tempo
  name: tempo
  namespace: tempo
spec:
  podMetricsEndpoints:
    - port: http-metrics
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
