apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: tempo
  name: tempo
  namespace: tempo
spec:
  endpoints:
  - interval: 30s
    targetPort: 3100
    path: /metrics
    scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/name: tempo
